### ISSUE TITLE
Mimecast 2FA doesn't work

### ISSUE THREAD

**Issue by cg-sis** [CarlGreenApps/OTP#1]
The code returned is invalid, adding the secret to WinAuth works.

**Comment by CarlGreenApps** [comment]
The library uses is returning wrong code, supplier has been notified and awaiting fix.
Looking at other options to workaround the issue.

**Comment by CarlGreenApps** [comment]
You can now use third party command line utility to obtain the correct totp code.
The Secret for the OTP item command would be:

Name:  TOTP
Secret:  t2otp.exe ABCDEFGHIJKLMOPQ

The command line tool must output the results in a DOS window and must exist in the same folder as OTP.exe

Tried and tested with: https://www.token2.com/shop/page/t2otp-exe-command-line-totp-generator
